"""Skill generation: the tool-level Skill (decisions/0020, generated
unconditionally by `index` regardless of vendor count or enrichment
status) and the per-vendor Skill + Cursor `.mdc` export (decisions/0013,
generated by usage-driven AI enrichment (`codecompass.enrichment`) as of
Phase 15 — decisions/0033 — after originally being generated by the now-
retired `promote`, decisions/0018).
"""

from __future__ import annotations

import shutil
import sqlite3
from pathlib import Path

from codecompass.core import VendorConfig, VendorDigest
from codecompass.graph import has_enrichment

_TOOL_SKILL_DIR_NAME = "codecompass"
_VENDOR_SKILL_DESCRIPTION_CAP = 400
_GRAPH_DB_FILENAME = "context-graph.db"


def _open_graph_readonly(project_root: Path) -> sqlite3.Connection | None:
    """`None` if `context-graph.db` doesn't exist yet. Same genuine
    read-only-connection, no-side-effect posture as `index.py`'s helper of
    the same name/shape — kept as a small local duplicate here rather than
    a shared import so this phase's `graph.py` diff stays scoped to just
    `has_enrichment` (see planning/phase-15-cli-rewire.md).
    """
    db_path = project_root / _GRAPH_DB_FILENAME
    if not db_path.exists():
        return None
    return sqlite3.connect(f"file:{db_path.as_posix()}?mode=ro", uri=True)


def render_tool_skill(configs: list[VendorConfig], project_root: Path) -> str:
    """Templated (non-AI) Skill describing codecompass's own commands and
    the current vendor list — present unconditionally, regardless of
    vendor count or enrichment status, so any agent working in the project
    has a mechanical signal that codecompass exists and that `codecompass
    query`/`check` are how to inspect coverage (decisions/0020). Enrichment
    status is graph-derived (`has_enrichment`), same sourcing as
    `index.py`'s routing table — `False` for every vendor if
    `context-graph.db` doesn't exist yet, rather than erroring.
    """
    conn = _open_graph_readonly(project_root)
    try:
        sorted_configs = sorted(configs, key=lambda c: c.name)
        enriched_by_name = {
            config.name: conn is not None and has_enrichment(conn, config.name)
            for config in sorted_configs
        }
    finally:
        if conn is not None:
            conn.close()

    enriched_count = sum(1 for enriched in enriched_by_name.values() if enriched)
    lines = [
        "---",
        "name: codecompass",
        "description: >-",
        "  Dependency reference docs for this project, generated by",
        "  codecompass. Use `codecompass query vendor <vendor>` to inspect a",
        "  dependency's usage/enrichment status; `codecompass check` to see",
        "  what's stale or uncovered.",
        "---",
        "",
        "# codecompass",
        "",
        "This project uses codecompass to keep AI-consultable dependency "
        "reference docs under `vendor/<name>/`, version-pinned to what's "
        "actually installed.",
        "",
        "## Commands",
        "",
        "- `codecompass sync [vendor]` — regenerate digests and trees; a "
        "whole-project sync also rebuilds the context graph and, for "
        "usage-proven vendors, auto-triggers disclosed AI enrichment.",
        "- `codecompass index` — refresh the root CLAUDE.md routing table "
        "and this Skill.",
        "- `codecompass check [--strict] [--fix]` — staleness + coverage "
        "gate (unused vendors, undocumented usage, orphaned skill "
        "mentions).",
        "- `codecompass query <subcommand>` — read the context graph "
        "(`context-graph.db`) without writing raw SQL:",
        "  - `query vendors [--unused] [--json]` — every tracked vendor, "
        "its usage/enrichment status.",
        "  - `query vendor <name> [--json]` — one vendor's full profile: "
        "symbols, usage count, documenting artifacts, routed Skill, "
        "`depends_on`.",
        "  - `query symbol <name> [--json]` — every symbol with this "
        "name across all vendors (names aren't globally unique), its "
        "purpose and usage count.",
        "  - `query skills [--unused-mentions] [--json]` — every "
        "Skill/`.mdc` rule in the project (not just codecompass's own) "
        "and what it mechanically mentions.",
        "  - `query relations <name> [--json]` — given a spec-doc path "
        "(e.g. `architecture/overview.md`), what it mechanically "
        "mentions; given a vendor or Skill name, which spec docs "
        "mechanically mention it.",
        "  - If a question doesn't fit any of these — an ad hoc join or "
        "filter — query `context-graph.db` directly with `sqlite3` (a "
        "plain SQLite file at the project root); see "
        "`architecture/overview.md`'s \"Context graph\" section for the "
        "schema (`vendors`, `symbols`, `uses_edges`, `doc_artifacts`, "
        "`documents_edges`, `skill_mentions_edges`, `routes_via_edges`, "
        "`depends_on_edges`, `doc_relations_edges`, `vendor_enrichment`, "
        "`symbol_enrichment`).",
        "- `/discovery` — a read-only guided-exploration slash command "
        "covering the same ground as `query`, for a human-initiated "
        "session that should never write, edit, or plan code changes.",
        "",
        f"## Vendors ({len(configs)} tracked, {enriched_count} enriched)",
        "",
        "| Name | Ecosystem | Enriched |",
        "|---|---|---|",
    ]
    for config in sorted_configs:
        enriched_label = "yes" if enriched_by_name[config.name] else "no"
        lines.append(f"| {config.name} | {config.ecosystem.value} | {enriched_label} |")
    return "\n".join(lines) + "\n"


def write_tool_skill(project_root: Path, configs: list[VendorConfig]) -> None:
    skill_dir = project_root / ".claude" / "skills" / _TOOL_SKILL_DIR_NAME
    skill_dir.mkdir(parents=True, exist_ok=True)
    (skill_dir / "SKILL.md").write_text(render_tool_skill(configs, project_root), encoding="utf-8")


def _vendor_skill_name(config: VendorConfig) -> str:
    """Always `codecompass-<vendor>` — can never collide with the
    tool-level Skill's bare `codecompass` name (decisions/0020).
    """
    return f"codecompass-{config.name}"


def render_vendor_skill(digest: VendorDigest) -> str:
    """Trigger description built from data already generated — a
    condensed conversational overview — not a new AI call
    (decisions/0013 pt 1). Description length is a real cost: every
    skill's name+description loads into every session's context
    unconditionally, so `_VENDOR_SKILL_DESCRIPTION_CAP` keeps it bounded.
    """
    config = digest.config
    overview = (digest.conversational_overview or "").strip()
    condensed = overview[:_VENDOR_SKILL_DESCRIPTION_CAP]
    description = (
        f"API questions, known gotchas, and internals for {config.name} "
        f"({config.ecosystem.value}), pinned to the installed version. {condensed}"
    ).strip()
    lines = [
        "---",
        f"name: {_vendor_skill_name(config)}",
        "description: >-",
        f"  {description}",
        "---",
        "",
        f"# {config.name}",
        "",
        f"Grounded description of the installed `{config.name}` "
        f"({digest.installed_version}), retrieved from its own upstream "
        f"repository — not from training knowledge. See "
        f"`vendor/{config.name}/CLAUDE.md` for the full per-vendor digest.",
        "",
    ]
    if digest.technical_description:
        lines += [digest.technical_description, ""]
    if digest.action_pointer_file:
        lines += [
            f"**Worth reading next:** `{digest.action_pointer_file}` — "
            f"{digest.action_pointer_note}",
            "",
        ]
    lines += [
        "## References",
        "",
        "- [references/FILETREE.md](./references/FILETREE.md)",
        "- [references/DEPTREE.md](./references/DEPTREE.md)",
    ]
    return "\n".join(lines) + "\n"


def write_vendor_skill(project_root: Path, digest: VendorDigest) -> None:
    """Bundles `FILETREE.md`/`DEPTREE.md` as `references/` files rather
    than inlining them into the main body — progressive disclosure, they
    only cost tokens once Claude actually needs to navigate source
    (decisions/0013 pt 2).
    """
    config = digest.config
    skill_dir = project_root / ".claude" / "skills" / _vendor_skill_name(config)
    references_dir = skill_dir / "references"
    references_dir.mkdir(parents=True, exist_ok=True)
    (skill_dir / "SKILL.md").write_text(render_vendor_skill(digest), encoding="utf-8")
    vendor_dir = project_root / "vendor" / config.name
    for filename in ("FILETREE.md", "DEPTREE.md"):
        source = vendor_dir / filename
        if source.exists():
            shutil.copyfile(source, references_dir / filename)


def render_cursor_mdc(digest: VendorDigest) -> str:
    """Cursor `.mdc` rule — glob-scoped activation is Cursor's own
    trigger model, different from Skills' description-matching. Retained
    alongside Skills, not replaced (decisions/0013 pt 4): some Cursor
    users may not have Skills support, and Cursor's per-file-pattern
    activation is in some cases more precise.
    """
    config = digest.config
    lines = [
        "---",
        f"description: API questions and known gotchas for {config.name} "
        f"({config.ecosystem.value})",
        "alwaysApply: false",
        "---",
        "",
        f"# {config.name}",
        "",
        f"Pinned to the installed version ({digest.installed_version}). See "
        f"`vendor/{config.name}/CLAUDE.md` for the full digest.",
        "",
    ]
    if digest.technical_description:
        lines += [digest.technical_description, ""]
    return "\n".join(lines) + "\n"


def write_cursor_mdc(project_root: Path, digest: VendorDigest) -> None:
    rules_dir = project_root / ".cursor" / "rules"
    rules_dir.mkdir(parents=True, exist_ok=True)
    (rules_dir / f"codecompass-{digest.config.name}.mdc").write_text(
        render_cursor_mdc(digest), encoding="utf-8"
    )
