"""Skill generation: the tool-level Skill (decisions/0020, generated
unconditionally by `index` regardless of vendor count or depth) and the
per-vendor Skill + Cursor `.mdc` export (decisions/0013, generated by
`promote` — decisions/0018 — rather than a separate later phase).
"""

from __future__ import annotations

import shutil
from pathlib import Path

from depcompass.core import Depth, VendorConfig, VendorDigest

_TOOL_SKILL_DIR_NAME = "depcompass"
_VENDOR_SKILL_DESCRIPTION_CAP = 400


def render_tool_skill(configs: list[VendorConfig]) -> str:
    """Templated (non-AI) Skill describing depcompass's own commands and
    the current vendor list — present unconditionally, regardless of
    vendor count or depth, so any agent working in the project has a
    mechanical signal that depcompass exists and that `promote` is where
    AI cost enters (decisions/0020).
    """
    full_count = sum(1 for c in configs if c.depth is Depth.FULL)
    lines = [
        "---",
        "name: depcompass",
        "description: >-",
        "  Dependency reference docs for this project, generated by",
        "  depcompass. Use `depcompass promote <vendor>` for a deeper,",
        "  AI-grounded digest of a specific dependency; `depcompass check`",
        "  to see what's stale.",
        "---",
        "",
        "# depcompass",
        "",
        "This project uses depcompass to keep AI-consultable dependency "
        "reference docs under `vendor/<name>/`, version-pinned to what's "
        "actually installed.",
        "",
        "## Commands",
        "",
        "- `depcompass sync [vendor]` — regenerate digests and trees.",
        "- `depcompass index` — refresh the root CLAUDE.md routing table.",
        "- `depcompass check [--strict] [--fix]` — staleness gate.",
        "- `depcompass promote <vendor>` — escalate one vendor to "
        "`depth = full`: a real AI call, cost-disclosed first.",
        "",
        f"## Vendors ({len(configs)} tracked, {full_count} at `full` depth)",
        "",
        "| Name | Ecosystem | Depth |",
        "|---|---|---|",
    ]
    for config in sorted(configs, key=lambda c: c.name):
        lines.append(f"| {config.name} | {config.ecosystem.value} | {config.depth.value} |")
    return "\n".join(lines) + "\n"


def write_tool_skill(project_root: Path, configs: list[VendorConfig]) -> None:
    skill_dir = project_root / ".claude" / "skills" / _TOOL_SKILL_DIR_NAME
    skill_dir.mkdir(parents=True, exist_ok=True)
    (skill_dir / "SKILL.md").write_text(render_tool_skill(configs), encoding="utf-8")


def _vendor_skill_name(config: VendorConfig) -> str:
    """Always `depcompass-<vendor>` — can never collide with the
    tool-level Skill's bare `depcompass` name (decisions/0020).
    """
    return f"depcompass-{config.name}"


def render_vendor_skill(digest: VendorDigest) -> str:
    """Trigger description built from data already generated — a
    condensed conversational overview — not a new AI call
    (decisions/0013 pt 1). Description length is a real cost: every
    skill's name+description loads into every session's context
    unconditionally, so `_VENDOR_SKILL_DESCRIPTION_CAP` keeps it bounded.
    """
    config = digest.config
    overview = (digest.conversational_overview or "").strip()
    condensed = overview[:_VENDOR_SKILL_DESCRIPTION_CAP]
    description = (
        f"API questions, known gotchas, and internals for {config.name} "
        f"({config.ecosystem.value}), pinned to the installed version. {condensed}"
    ).strip()
    lines = [
        "---",
        f"name: {_vendor_skill_name(config)}",
        "description: >-",
        f"  {description}",
        "---",
        "",
        f"# {config.name}",
        "",
        f"Grounded description of the installed `{config.name}` "
        f"({digest.installed_version}), retrieved from its own upstream "
        f"repository — not from training knowledge. See "
        f"`vendor/{config.name}/CLAUDE.md` for the full per-vendor digest.",
        "",
    ]
    if digest.technical_description:
        lines += [digest.technical_description, ""]
    if digest.action_pointer_file:
        lines += [
            f"**Worth reading next:** `{digest.action_pointer_file}` — "
            f"{digest.action_pointer_note}",
            "",
        ]
    lines += [
        "## References",
        "",
        "- [references/FILETREE.md](./references/FILETREE.md)",
        "- [references/DEPTREE.md](./references/DEPTREE.md)",
    ]
    return "\n".join(lines) + "\n"


def write_vendor_skill(project_root: Path, digest: VendorDigest) -> None:
    """Bundles `FILETREE.md`/`DEPTREE.md` as `references/` files rather
    than inlining them into the main body — progressive disclosure, they
    only cost tokens once Claude actually needs to navigate source
    (decisions/0013 pt 2).
    """
    config = digest.config
    skill_dir = project_root / ".claude" / "skills" / _vendor_skill_name(config)
    references_dir = skill_dir / "references"
    references_dir.mkdir(parents=True, exist_ok=True)
    (skill_dir / "SKILL.md").write_text(render_vendor_skill(digest), encoding="utf-8")
    vendor_dir = project_root / "vendor" / config.name
    for filename in ("FILETREE.md", "DEPTREE.md"):
        source = vendor_dir / filename
        if source.exists():
            shutil.copyfile(source, references_dir / filename)


def render_cursor_mdc(digest: VendorDigest) -> str:
    """Cursor `.mdc` rule — glob-scoped activation is Cursor's own
    trigger model, different from Skills' description-matching. Retained
    alongside Skills, not replaced (decisions/0013 pt 4): some Cursor
    users may not have Skills support, and Cursor's per-file-pattern
    activation is in some cases more precise.
    """
    config = digest.config
    lines = [
        "---",
        f"description: API questions and known gotchas for {config.name} "
        f"({config.ecosystem.value})",
        "alwaysApply: false",
        "---",
        "",
        f"# {config.name}",
        "",
        f"Pinned to the installed version ({digest.installed_version}). See "
        f"`vendor/{config.name}/CLAUDE.md` for the full digest.",
        "",
    ]
    if digest.technical_description:
        lines += [digest.technical_description, ""]
    return "\n".join(lines) + "\n"


def write_cursor_mdc(project_root: Path, digest: VendorDigest) -> None:
    rules_dir = project_root / ".cursor" / "rules"
    rules_dir.mkdir(parents=True, exist_ok=True)
    (rules_dir / f"depcompass-{digest.config.name}.mdc").write_text(
        render_cursor_mdc(digest), encoding="utf-8"
    )
